[2024-08-12T17:27:15.687+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.add_country_column scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-12T17:27:15.697+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.add_country_column scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-12T17:27:15.698+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-12T17:27:15.698+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2024-08-12T17:27:15.699+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-12T17:27:15.710+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): add_country_column> on 2024-08-11 00:00:00+00:00
[2024-08-12T17:27:15.717+0000] {standard_task_runner.py:55} INFO - Started process 318 to run task
[2024-08-12T17:27:15.721+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'add_country_column', 'scheduled__2024-08-11T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpr4nuxb_r']
[2024-08-12T17:27:15.724+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask add_country_column
[2024-08-12T17:27:15.790+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.add_country_column scheduled__2024-08-11T00:00:00+00:00 [running]> on host a76316aa0937
[2024-08-12T17:27:15.852+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=add_country_column
AIRFLOW_CTX_EXECUTION_DATE=2024-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-11T00:00:00+00:00
[2024-08-12T17:27:15.863+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-08-12T17:27:15.869+0000] {sql.py:315} INFO - Running statement: 
            ALTER TABLE users
            ADD COLUMN country TEXT NOT NULL;
        , parameters: None
[2024-08-12T17:27:15.871+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateColumn: column "country" of relation "users" already exists

[2024-08-12T17:27:15.881+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=add_country_column, execution_date=20240811T000000, start_date=20240812T172715, end_date=20240812T172715
[2024-08-12T17:27:15.890+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 65 for task add_country_column (column "country" of relation "users" already exists
; 318)
[2024-08-12T17:27:15.935+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-12T17:27:15.963+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
